### PR TITLE
Added Style to dropdown 

### PR DESCRIPTION
**Pull request by swapnadeepmohapatra**
Added Styles to the dropdown in the Desktop Version. 

This is how the Dropdown Looks LIke.

image

This PR refers to issue #2 

Thank you maintainer for maintaining this project.

### CODE REVIEW

**Comment by FidalMathew** [comment]
Thank you for contributing, I had a suggestion.
image

Try to make the dropdown smaller, similar to that picture. Sorry, I didn't mention that earlier

**Comment by FidalMathew** [comment]
By the way, U did a great job!

**Comment by swapnadeepmohapatra** [comment]
I have changed the CSS. Please do take a look. 

image

**Comment by FidalMathew** [comment]
Great Job!

**Comment by FidalMathew** [comment]
Could you deploy it on Github pages?

**Comment by swapnadeepmohapatra** [comment]
You can view it here. 

https://s9fk5.csb.app/

**Comment by FidalMathew** [comment]
Thank you for contributing!! It was a pleasure :)

**Comment by FidalMathew** [comment]
@swapnadeepmohapatra  I would love to connect with you! checkout your Github and Twitter

**Pull request merged**
