### PR TITLE
Added footer

### PR DESCRIPTION
**Pull request by AnikaJagati**
Made changes to the index.html and style.css files to add the footer.

Hope it helps :)

### CODE REVIEW

**Comment by FidalMathew** [comment]
I will look into it, thanks for your contribution.

**Comment by FidalMathew** [comment]
Don't you think you should have added the footer inside the <body> tag?
image

Also, do provide the image of your work and do host it on GitHub pages. Btw, you have done great work 👍.

**Comment by AnikaJagati** [comment]
> Don't you think you should have added the footer inside the tag? image
> 
> Also, do provide the image of your work and do host it on GitHub pages. Btw, you have done great work 👍.

hey ,which tag are you talking about btw?

**Comment by FidalMathew** [comment]
yup, I have never seen a footer tag outside the body tag.
image
-this tag

**Comment by AnikaJagati** [comment]
> yup, I have never seen a footer tag outside the body tag. image -this tag

Well it doesn't really make a difference to the content as it comes at the end and is still visible 
But I've changed it and if it helps then do accept the pull request.
Thanks :)

**Comment by FidalMathew** [comment]
image
Give me some time @AnikaJagati, This issue is generated because there was an earlier PR that was merged and you did your commit in the previous version.

OR @AnikaJagati if possible, try to update your branch with the current master branch. And then add the footer

Waiting for your reply

**Comment by FidalMathew** [comment]
And do try to give the link of the changes u have made (deployment), it will better

**Comment by AnikaJagati** [comment]
Hey , i created another pull request on the updated master and has no conflicts.
Lemme know 

And the links for the updated files are(from the forked repo):
[https://github.com/AnikaJagati/apple.com/blob/master/index.html](url)
[https://github.com/AnikaJagati/apple.com/blob/master/style.css](url)

**Pull request closed without merging**
